<Project>

  <Import Project="..\MonoGame.props" />

  <PropertyGroup>
    <MonoGamePlatform>$(MSBuildProjectName.Substring(19))</MonoGamePlatform>
    <BaseIntermediateOutputPath Condition="'$(UseArtifactsOutput)' != 'true'">obj\$(MonoGamePlatform)</BaseIntermediateOutputPath>
    <BaseOutputPath Condition="'$(UseArtifactsOutput)' != 'true'">..\Artifacts\MonoGame.Framework\$(MonoGamePlatform)</BaseOutputPath>
    <AssemblyName>MonoGame.Framework</AssemblyName>
    <RootNamespace>Microsoft.Xna.Framework</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

</Project>
